# Generated by Django 4.0.2 on 2022-04-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pasword', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=7)),
            ],
        ),
    ]
