# Generated by Django 4.0.2 on 2022-04-16 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='pasword',
            new_name='password',
        ),
    ]
